Repository kevinlie19/tes, pull requests merged in 2019-09, with the labels that each got.

#9 [Back-End] Fixing Setup Backend
  back-end/.babelrc
  back-end/.env.example
  back-end/.eslintrc.js
  back-end/.gitignore
  back-end/.prettierignore
  back-end/nodemon.json
  back-end/package-lock.json
  back-end/package.json
  back-end/src/config/constants.ts
  back-end/src/config/db.ts
  back-end/src/config/router.ts
  back-end/src/index.ts
  back-end/yarn.lock
Labels: Approved

#12 [Front-End] Fix Icon, Add LogoBig
  front-end/assets/Images/logoBig.png
  front-end/src/core-ui/Icon.tsx
Labels: Need Review

#11 [Front-End] Welcome Scenes and color: LIGHT_BLACK
  front-end/src/constants/color.ts
  front-end/src/scenes/WelcomeScenes.tsx
Labels: Approved

#10 [Front-End] Add Core-UI TextInput
  front-end/src/core-ui/TextInput.tsx
Labels: Approved with Minor Fix

#13 [Front-End] Fixing Core-UI TextInput
  front-end/src/core-ui/TextInput.tsx
  front-end/src/core-ui/index.ts
Labels: Approved

#14 [Front-End] Setup React Navigation
  front-end/package.json
  front-end/src/configs/routes/AppStack.ts
  front-end/src/configs/routes/AuthStack.ts
  front-end/src/configs/routes/Navigator.ts
  front-end/src/constants/api.ts
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/SignInScene.tsx
  front-end/src/scenes/SignUpScene.tsx
  front-end/src/scenes/SplashScene.tsx
  front-end/src/scenes/WelcomeScene.tsx
Labels: Approved

#15 [Front-End] Add WelcomeCard, WelcomeScene, MinorFix
  front-end/src/components/WelcomeCard.tsx
  front-end/src/components/index.ts
  front-end/src/configs/routes/AppStack.ts
  front-end/src/configs/routes/AuthStack.ts
  front-end/src/core-ui/Text.tsx
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/SignInScene.tsx
  front-end/src/scenes/SignUpScene.tsx
  front-end/src/scenes/SplashScene.tsx
  front-end/src/scenes/WelcomeScene.tsx
Labels: Approved

#17 [Front-End] [Scenes]Add HomeScene & MinorFix everything
  front-end/src/components/EventList.tsx
  front-end/src/components/WelcomeCard.tsx
  front-end/src/configs/routes/AppStack.ts
  front-end/src/core-ui/Icon.tsx
  front-end/src/core-ui/Image.tsx
  front-end/src/core-ui/Text.tsx
  front-end/src/scenes/ConfirmUpgradeMembershipScene.tsx
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/InboxScene.tsx
  front-end/src/scenes/MyAccountScene.tsx
  front-end/src/scenes/SplashScene.tsx
  front-end/src/scenes/UpgradeMembershipScene.tsx
Labels: Need Review

#18 Add HomeScene & MinorFix everything (#17) V.2
  front-end/src/components/EventList.tsx
  front-end/src/scenes/HomeScene.tsx
Labels: Approved

#19 [Front-End] [Scenes] Add MyAccountScene & MinorFix
  front-end/src/components/index.ts
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/MyAccountScene.tsx
Labels: Approved

#16 [Front-End] [component] Sign in card and Sign Up card
  front-end/src/components/SignIn.tsx
  front-end/src/components/SignUp.tsx
Labels: Approved with Minor Fix

#20 MinorFix Components
  front-end/src/components/SignIn.tsx
  front-end/src/components/SignInCard.tsx
  front-end/src/components/SignUp.tsx
  front-end/src/components/SignUpCard.tsx
  front-end/src/components/index.ts
Labels: Need Review

#21 [Front-End] [Scenes] Add SignInScene & SignUpScene
  front-end/src/components/SignInCard.tsx
  front-end/src/components/SignUpCard.tsx
  front-end/src/scenes/SignInScene.tsx
  front-end/src/scenes/SignUpScene.tsx
Labels: Need Review

#23 [Front-End] Add Redux & Connect Splash-Home & MyAccountScene
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/SignInCard.tsx
  front-end/src/components/SignUpCard.tsx
  front-end/src/configs/createDataStore.ts
  front-end/src/configs/rootReducer.ts
  front-end/src/configs/rootSaga.ts
  front-end/src/core-ui/Avatar.tsx
  front-end/src/helpers/NavigationHelper.ts
  front-end/src/helpers/index.ts
  front-end/src/helpers/token.ts
  front-end/src/reducers/accountReducer.ts
  front-end/src/reducers/signinReducer.ts
  front-end/src/reducers/signupReducer.ts
  front-end/src/reducers/welcomeReducer.ts
  front-end/src/sagas/accountSaga.ts
  front-end/src/sagas/signinSaga.ts
  front-end/src/sagas/signupSaga.ts
  front-end/src/sagas/welcomeSaga.ts
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/MyAccountScene.tsx
  front-end/src/scenes/SignInScene.tsx
  front-end/src/scenes/SignUpScene.tsx
  front-end/src/scenes/SplashScene.tsx
  front-end/src/scenes/WelcomeScene.tsx
  front-end/src/types/Commons.ts
  front-end/src/types/MyAccountSceneType.ts
  front-end/src/types/SignInSceneType.ts
  front-end/src/types/SignUpSceneType.ts
  front-end/src/types/State.ts
  front-end/src/types/WelcomeSceneType.ts
Labels: Approved with Minor Fix

#24 [Back-End] New setup for Back-End
  back-end/src/cloudinarySetup.ts
  back-end/src/cloudinaryType.d.ts
  back-end/src/config/constants.ts
  back-end/src/config/db.ts
  back-end/src/config/router.ts
  back-end/src/constants/index.ts
  back-end/src/controllers/authController.ts
  back-end/src/controllers/errorController.ts
  back-end/src/controllers/featureController.ts
  back-end/src/controllers/index.ts
  back-end/src/controllers/pageController.ts
  back-end/src/db.ts
  back-end/src/helpers/index.ts
  back-end/src/index.ts
  back-end/src/middleware.ts
  back-end/src/models/userModel.ts
  back-end/src/routers/authRouter.ts
  back-end/src/routers/featureRouter.ts
  back-end/src/routers/index.ts
  back-end/src/routers/pageRouter.ts
  back-end/src/types/index.ts
Labels: Approved

#25 MinorFix for LoginGoogle & MyAccount
  front-end/src/configs/rootReducer.ts
  front-end/src/configs/rootSaga.ts
  front-end/src/reducers/accountReducer.ts
  front-end/src/sagas/accountSaga.ts
  front-end/src/sagas/welcomeSaga.ts
  front-end/src/scenes/MyAccountScene.tsx
  front-end/src/scenes/WelcomeScene.tsx
  front-end/src/types/Commons.ts
  front-end/src/types/MyAccountSceneType.ts
  front-end/src/types/WelcomeSceneType.ts
Labels: Approved

#26 MinorFix LoginGoogle V.2
  front-end/src/sagas/signinSaga.ts
  front-end/src/sagas/signupSaga.ts
  front-end/src/sagas/welcomeSaga.ts
  front-end/src/scenes/WelcomeScene.tsx
Labels: Approved

#27 [Front-End] [Scenes] Add EventScene
  front-end/src/components/EventList.tsx
  front-end/src/components/SignUpCard.tsx
  front-end/src/configs/rootReducer.ts
  front-end/src/configs/rootSaga.ts
  front-end/src/configs/routes/AppStack.ts
  front-end/src/reducers/homeReducer.ts
  front-end/src/sagas/homeSaga.ts
  front-end/src/scenes/EventScene.tsx
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/SignUpScene.tsx
  front-end/src/scenes/TransactionScene.tsx
  front-end/src/types/Commons.ts
  front-end/src/types/HomeSceneType.ts
  front-end/src/types/State.ts
Labels: Approved

#28 [Back-End] Update BackEnd for Events
  back-end/src/controllers/authController.ts
  back-end/src/controllers/featureController.ts
  back-end/src/controllers/pageController.ts
  back-end/src/index.ts
  back-end/src/models/eventModel.ts
  back-end/src/models/userModel.ts
  back-end/src/routers/featureRouter.ts
  back-end/src/routers/pageRouter.ts
  back-end/src/types/index.ts
Labels: Approved

#29 [Front-End] [Scenes] Add EventDetailScene and MinorFix to support all flow
  front-end/package.json
  front-end/src/components/EventList.tsx
  front-end/src/components/SignInCard.tsx
  front-end/src/components/SignUpCard.tsx
  front-end/src/components/WelcomeCard.tsx
  front-end/src/configs/rootReducer.ts
  front-end/src/configs/rootSaga.ts
  front-end/src/configs/routes/AppStack.ts
  front-end/src/constants/color.ts
  front-end/src/core-ui/Button.tsx
  front-end/src/core-ui/Image.tsx
  front-end/src/core-ui/Text.tsx
  front-end/src/helpers/eventID.ts
  front-end/src/helpers/index.ts
  front-end/src/reducers/eventDetailReducer.ts
  front-end/src/reducers/homeReducer.ts
  front-end/src/sagas/eventDetailSaga.ts
  front-end/src/scenes/EventDetailScene.tsx
  front-end/src/scenes/EventScene.tsx
  front-end/src/scenes/HomeScene.tsx
  front-end/src/scenes/MyAccountScene.tsx
  front-end/src/types/Commons.ts
  front-end/src/types/EventDetailSceneType.ts
  front-end/src/types/State.ts
Labels: Approved
